#!/usr/bin/env python3
"""Demo - Exercise the protease_pipeline helper library directly.

The numbered stage scripts wrap external tools (RFdiffusion, PyRosetta,
ProteinMPNN/FastRelax, AlphaFold3) that this repo doesn't bundle, so a few of
the shared helpers in protease_pipeline/ (used inside those scripts, or by the
external MPNN/FastRelax driver they hand off to) never get exercised by the
runnable part of the demo. This script calls them directly against the
synthetic design model in design/round1_mpnn_fr/pdbs/helixA.pdb, generated by
generate_demo_data.py.

Run from the demo/ directory:  python demo_library_functions.py
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from protease_pipeline import constraints, geometry, pdb_utils

DESIGN_MODEL = "design/round1_mpnn_fr/pdbs/helixA.pdb"


def main():
    print(f"Reading {DESIGN_MODEL} ...\n")

    cys, his, asp = pdb_utils.extract_first_catalytic_residues(DESIGN_MODEL)
    print(f"Catalytic triad (chain A): Cys{cys}, His{his}, Asp{asp}")

    key_residues = pdb_utils.key_residues_from_chainA(DESIGN_MODEL)
    print(f"Chain-A catalytic residue numbers: {sorted(key_residues)}")

    fixed = pdb_utils.get_non_alanine_residues(DESIGN_MODEL)
    print(f"Non-alanine (FIXED-candidate) positions: {fixed}")

    sequences = pdb_utils.extract_chain_sequences(DESIGN_MODEL, chains=("A", "B"))
    for chain_id, seq in sequences.items():
        print(f"Chain {chain_id} sequence: {seq}")

    chain_a_length = len(sequences["A"])
    cst_text = constraints.catalytic_triad_constraints(
        his=his, asp=asp, cys=cys, chain_a_length=chain_a_length,
    )
    print("\nGenerated Rosetta constraint block (pose numbering):")
    print(cst_text)

    rmsd = geometry.calculate_ca_rmsd(
        DESIGN_MODEL,
        "af3/round3_apo/pdbs/candidate_01_apo.pdb",
        chain1="A", chain2="A",
    )
    print(f"CA-RMSD, chain A of helixA.pdb vs. candidate_01_apo.pdb: {rmsd:.3f} A")


if __name__ == "__main__":
    main()
